// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Mode string

const (
	ModeUPI        Mode = "UPI"
	ModeCARD       Mode = "CARD"
	ModeNETBANKING Mode = "NETBANKING"
)

func (e *Mode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Mode(s)
	case string:
		*e = Mode(s)
	default:
		return fmt.Errorf("unsupported scan type for Mode: %T", src)
	}
	return nil
}

type NullMode struct {
	Mode  Mode `json:"mode"`
	Valid bool `json:"valid"` // Valid is true if Mode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMode) Scan(value interface{}) error {
	if value == nil {
		ns.Mode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Mode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Mode), nil
}

type TransactionDecision string

const (
	TransactionDecisionALLOW       TransactionDecision = "ALLOW"
	TransactionDecisionFLAG        TransactionDecision = "FLAG"
	TransactionDecisionBLOCK       TransactionDecision = "BLOCK"
	TransactionDecisionMFAREQUIRED TransactionDecision = "MFA_REQUIRED"
)

func (e *TransactionDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionDecision(s)
	case string:
		*e = TransactionDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionDecision: %T", src)
	}
	return nil
}

type NullTransactionDecision struct {
	TransactionDecision TransactionDecision `json:"transaction_decision"`
	Valid               bool                `json:"valid"` // Valid is true if TransactionDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionDecision) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionDecision), nil
}

type TriggerFactors string

const (
	TriggerFactorsAMOUNTDEVIATION TriggerFactors = "AMOUNT_DEVIATION"
	TriggerFactorsFREQUENCYSPIKE  TriggerFactors = "FREQUENCY_SPIKE"
	TriggerFactorsNEWMODE         TriggerFactors = "NEW_MODE"
	TriggerFactorsTIMEANOMALY     TriggerFactors = "TIME_ANOMALY"
)

func (e *TriggerFactors) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerFactors(s)
	case string:
		*e = TriggerFactors(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerFactors: %T", src)
	}
	return nil
}

type NullTriggerFactors struct {
	TriggerFactors TriggerFactors `json:"trigger_factors"`
	Valid          bool           `json:"valid"` // Valid is true if TriggerFactors is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerFactors) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerFactors, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerFactors.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerFactors) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerFactors), nil
}

type Transaction struct {
	ID               int32               `json:"id"`
	UserID           int32               `json:"user_id"`
	Amount           int32               `json:"amount"`
	Mode             Mode                `json:"mode"`
	RiskScore        int32               `json:"risk_score"`
	TriggeredFactors []string            `json:"triggered_factors"`
	Decision         TransactionDecision `json:"decision"`
	CreatedAt        pgtype.Timestamp    `json:"created_at"`
	UpdatedAt        pgtype.Timestamp    `json:"updated_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	MobileNumber string           `json:"mobile_number"`
	HashedPass   string           `json:"hashed_pass"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type UserProfileBehavior struct {
	UserID                            int32            `json:"user_id"`
	AverageTransactionAmount          pgtype.Int4      `json:"average_transaction_amount"`
	MaxTransactionAmountSeen          pgtype.Int4      `json:"max_transaction_amount_seen"`
	AverageNumberOfTransactionsPerDay pgtype.Int4      `json:"average_number_of_transactions_per_day"`
	RegisteredPaymentModes            []Mode           `json:"registered_payment_modes"`
	UsualTransactionStartHour         pgtype.Timestamp `json:"usual_transaction_start_hour"`
	UsualTransactionEndHour           pgtype.Timestamp `json:"usual_transaction_end_hour"`
	TotalTransactions                 int32            `json:"total_transactions"`
	AllowedTransactions               int32            `json:"allowed_transactions"`
	UpdatedAt                         pgtype.Timestamp `json:"updated_at"`
}
