// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repository

import (
	"context"
)

const countRecentTransactions = `-- name: CountRecentTransactions :one
SELECT COUNT(*)
FROM transactions
WHERE user_id = $1
AND created_at > NOW() - make_interval(secs => $2)
`

type CountRecentTransactionsParams struct {
	UserID int32   `json:"user_id"`
	Secs   float64 `json:"secs"`
}

func (q *Queries) CountRecentTransactions(ctx context.Context, arg CountRecentTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentTransactions, arg.UserID, arg.Secs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodaysTransactions = `-- name: CountTodaysTransactions :one
SELECT COUNT(*)
FROM transactions
WHERE user_id = $1
AND created_at >= CURRENT_DATE
`

func (q *Queries) CountTodaysTransactions(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countTodaysTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    amount,
    type,
    mode,
    risk_score,
    triggered_factors,
    decision,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, user_id, amount, type, mode, risk_score, triggered_factors, decision, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID           int32               `json:"user_id"`
	Amount           int32               `json:"amount"`
	Type             TransactionType     `json:"type"`
	Mode             Mode                `json:"mode"`
	RiskScore        int32               `json:"risk_score"`
	TriggeredFactors []TriggerFactors    `json:"triggered_factors"`
	Decision         TransactionDecision `json:"decision"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Mode,
		arg.RiskScore,
		arg.TriggeredFactors,
		arg.Decision,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.Mode,
		&i.RiskScore,
		&i.TriggeredFactors,
		&i.Decision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllTransactionsByUserID = `-- name: GetAllTransactionsByUserID :many
SELECT id, user_id, amount, type, mode, risk_score, triggered_factors, decision, created_at, updated_at FROM transactions
WHERE user_id = $1
LIMIT 20 OFFSET 40
`

func (q *Queries) GetAllTransactionsByUserID(ctx context.Context, userID int32) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getAllTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Mode,
			&i.RiskScore,
			&i.TriggeredFactors,
			&i.Decision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyTransactionStats = `-- name: GetDailyTransactionStats :one
SELECT
    COUNT(*)                        AS total_transactions,
    COALESCE(AVG(amount), 0)::INT   AS average_amount,
    MIN(created_at)                 AS first_transaction_time,
    MAX(created_at)                 AS last_transaction_time
FROM transactions
WHERE user_id = $1
  AND created_at >= CURRENT_DATE
`

type GetDailyTransactionStatsRow struct {
	TotalTransactions    int64       `json:"total_transactions"`
	AverageAmount        int32       `json:"average_amount"`
	FirstTransactionTime interface{} `json:"first_transaction_time"`
	LastTransactionTime  interface{} `json:"last_transaction_time"`
}

func (q *Queries) GetDailyTransactionStats(ctx context.Context, userID int32) (GetDailyTransactionStatsRow, error) {
	row := q.db.QueryRow(ctx, getDailyTransactionStats, userID)
	var i GetDailyTransactionStatsRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.AverageAmount,
		&i.FirstTransactionTime,
		&i.LastTransactionTime,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, user_id, amount, type, mode, risk_score, triggered_factors, decision, created_at, updated_at FROM transactions
LIMIT 20 OFFSET 40
`

func (q *Queries) GetTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Mode,
			&i.RiskScore,
			&i.TriggeredFactors,
			&i.Decision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
