// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentTransactions = `-- name: CountRecentTransactions :one
SELECT COUNT(*)
FROM transactions
WHERE user_id = $1
AND created_at > NOW() - make_interval(secs => $2)
`

type CountRecentTransactionsParams struct {
	UserID int32   `json:"user_id"`
	Secs   float64 `json:"secs"`
}

func (q *Queries) CountRecentTransactions(ctx context.Context, arg CountRecentTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentTransactions, arg.UserID, arg.Secs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodaysTransactions = `-- name: CountTodaysTransactions :one
SELECT COUNT(*)
FROM transactions
WHERE user_id = $1
AND created_at >= CURRENT_DATE
`

func (q *Queries) CountTodaysTransactions(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countTodaysTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    amount,
    mode,
    risk_score,
    triggered_factors,
    decision,
    amount_deviation_score,
    frequency_deviation_score,
    mode_deviation_score,
    time_deviation_score,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::text[]::trigger_factors[],   
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    NOW()
)
RETURNING
    id,
    user_id,
    amount,
    mode,
    risk_score,
    triggered_factors::text[] AS triggered_factors, 
    decision,
    created_at,
    updated_at
`

type CreateTransactionParams struct {
	UserID                  int32               `json:"user_id"`
	Amount                  float64             `json:"amount"`
	Mode                    Mode                `json:"mode"`
	RiskScore               int32               `json:"risk_score"`
	Column5                 []string            `json:"column_5"`
	Decision                TransactionDecision `json:"decision"`
	AmountDeviationScore    int32               `json:"amount_deviation_score"`
	FrequencyDeviationScore int32               `json:"frequency_deviation_score"`
	ModeDeviationScore      int32               `json:"mode_deviation_score"`
	TimeDeviationScore      int32               `json:"time_deviation_score"`
	CreatedAt               pgtype.Timestamp    `json:"created_at"`
}

type CreateTransactionRow struct {
	ID               int32               `json:"id"`
	UserID           int32               `json:"user_id"`
	Amount           float64             `json:"amount"`
	Mode             Mode                `json:"mode"`
	RiskScore        int32               `json:"risk_score"`
	TriggeredFactors []string            `json:"triggered_factors"`
	Decision         TransactionDecision `json:"decision"`
	CreatedAt        pgtype.Timestamp    `json:"created_at"`
	UpdatedAt        pgtype.Timestamp    `json:"updated_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Mode,
		arg.RiskScore,
		arg.Column5,
		arg.Decision,
		arg.AmountDeviationScore,
		arg.FrequencyDeviationScore,
		arg.ModeDeviationScore,
		arg.TimeDeviationScore,
		arg.CreatedAt,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Mode,
		&i.RiskScore,
		&i.TriggeredFactors,
		&i.Decision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllTransactionsByUserID = `-- name: GetAllTransactionsByUserID :many
SELECT id, user_id, amount, mode, risk_score, triggered_factors, decision, amount_deviation_score, frequency_deviation_score, mode_deviation_score, time_deviation_score, created_at, updated_at FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllTransactionsByUserIDParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllTransactionsByUserID(ctx context.Context, arg GetAllTransactionsByUserIDParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getAllTransactionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Mode,
			&i.RiskScore,
			&i.TriggeredFactors,
			&i.Decision,
			&i.AmountDeviationScore,
			&i.FrequencyDeviationScore,
			&i.ModeDeviationScore,
			&i.TimeDeviationScore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyTransactionStats = `-- name: GetDailyTransactionStats :one
SELECT
    COUNT(*)                        AS total_transactions,
    COALESCE(AVG(amount), 0)::INT   AS average_amount,
    MIN(created_at)                 AS first_transaction_time,
    MAX(created_at)                 AS last_transaction_time
FROM transactions
WHERE user_id = $1
  AND created_at >= CURRENT_DATE
`

type GetDailyTransactionStatsRow struct {
	TotalTransactions    int64       `json:"total_transactions"`
	AverageAmount        int32       `json:"average_amount"`
	FirstTransactionTime interface{} `json:"first_transaction_time"`
	LastTransactionTime  interface{} `json:"last_transaction_time"`
}

func (q *Queries) GetDailyTransactionStats(ctx context.Context, userID int32) (GetDailyTransactionStatsRow, error) {
	row := q.db.QueryRow(ctx, getDailyTransactionStats, userID)
	var i GetDailyTransactionStatsRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.AverageAmount,
		&i.FirstTransactionTime,
		&i.LastTransactionTime,
	)
	return i, err
}

const getTransactionByTxnID = `-- name: GetTransactionByTxnID :one
SELECT id, user_id, amount, mode, risk_score, triggered_factors, decision, amount_deviation_score, frequency_deviation_score, mode_deviation_score, time_deviation_score, created_at, updated_at FROM transactions
WHERE id = $1 AND user_id = $2
`

type GetTransactionByTxnIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetTransactionByTxnID(ctx context.Context, arg GetTransactionByTxnIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByTxnID, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Mode,
		&i.RiskScore,
		&i.TriggeredFactors,
		&i.Decision,
		&i.AmountDeviationScore,
		&i.FrequencyDeviationScore,
		&i.ModeDeviationScore,
		&i.TimeDeviationScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
